### ISSUE TITLE
PHP Errors

### ISSUE THREAD

**Issue by aminemarref** [ForumHulp/Export-Import-Users#10]
Hello,

I use phpBB version 3.2.4 with php version 7.2.12.

When I click on "Ex- Import Users" in "Users and Groups" I get the following error message on the top of the control panel. 

`[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/acp/exportimportusers_module.php on line 414: sizeof(): Parameter must be an array or an object that implements Countable`
`[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 67: scandir(./..//store/user_updates,./..//store/user_updates): The system cannot find the file specified. (code: 2)`
`[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 67: scandir(./..//store/user_updates): failed to open dir: No such file or directory`
`[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 67: scandir(): (errno 2): No such file or directory`
`[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 67: array_diff(): Argument #1 is not an array`
`[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 69: Invalid argument supplied for foreach()`

I haven't used the upload functionality yet. I wanted to enquire about this first.

Thanks,
Amine.

**Comment by ForumHulp** [comment]
Solved your problem

 

 

Greetz

 

 

Van: Amine <notifications@github.com> 
Verzonden: zondag 16 december 2018 10:01
Aan: ForumHulp/Export-Import-Users <Export-Import-Users@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ForumHulp/Export-Import-Users] PHP Errors (#10)

 

Hello,

I use phpBB version 3.2.4 with php version 7.2.12.

When I click on "Ex- Import Users" in "Users and Groups" I get the following error message on the top of the control panel.

[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/acp/exportimportusers_module.php on line 414: sizeof(): Parameter must be an array or an object that implements Countable
[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 67: scandir(./..//store/user_updates,./..//store/user_updates): The system cannot find the file specified. (code: 2)
[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 67: scandir(./..//store/user_updates): failed to open dir: No such file or directory
[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 67: scandir(): (errno 2): No such file or directory
[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 67: array_diff(): Argument #1 is not an array
[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/exportimportusers/helper/functions_export_import_users.php on line 69: Invalid argument supplied for foreach()

I haven't used the upload functionality yet. I wanted to enquire about this first.

Thanks,
Amine.
