### ISSUE TITLE
Import Clear-Password and Usergroup?

### ISSUE THREAD

**Issue by nounours77** [ForumHulp/Export-Import-Users#8]
Hi John,

Thanks for this extension. Installing on a fresh 3.2.1 install went smooth!

As I want to use this to import a list of 3000 users, I'm interested in following features (_as the current version is not really useable to create users from external data_) - do you have any plans to go into this direction?

1) Import a clear-password, which will automatically hashed.

2) Import the Usergroup(s) which should be assigned to the user.

(_This two features are important if you want create users from external data!_)

less important:

3) Import custom fields (you export them all, but don't import)

4) Sending a mail to the user, informing about account creation, and tell him username / password (there was an older *.csv importer, which created a user, autocreated the password and mailed it).

thank you very much for considering this suggestion and for your good work!

Gilbert

**Comment by Galixte** [comment]
Hi @ForumHulp,

could you take a look, please?

**Comment by ForumHulp** [comment]
Hi Gilbert, 
i will think about.

Greetz

**Comment by nounours77** [comment]
Hi John,
In the meantime, I solved my import. I want to report back here, in case somebody else has the same problem.
1) Clear Password: I hacked the file " ", so that the password is hashed. This would be could to include as an option, but I've no clue how. Here is how I patched:
Line 86 & Line 100: 'user_password'	=> phpbb_hash($value['user_password']),
add line 373:    $value['user_password']=phpbb_hash($value['user_password']);
I then created the XML-file from my Excel-List with the clear password and imported it.

2) Assign the user group AFTER import. I prepared a list of the Login-Names in my Excel file, copied this list to the ACP (Manage Group, select the group, add the users from the list).

3) I managed to add Custom Fields in the XML, and it was imported. I think I got something wrong when I stated that importing custom fields was not possible. Anyway, it worked for me.

4) I sent every user a mail using mass-mailing function in the ACP. I could not find out how to specify the username (and password, but which maybe would't have been a good idea anyway), but since I took it over from a other system in a systematic way, I just wrote my users: "Your login is your firstname_lastname, and the password is the one you used on the old system".

So, with a bit of tweeking, I was able to achive my job using your import/export module. 

Hope this short description will help somebody, and thank you John for your help!

Gilbert

**Comment by Galixte** [comment]
Hi @ForumHulp,

could you take a look, please?

**Comment by ForumHulp** [comment]
New users should get a email now with their pass and login

**Comment by Galixte** [comment]
Thanks you so much @ForumHulp!
