### ISSUE TITLE
Not visible for "user and group"-admin

### ISSUE THREAD

**Issue by Turrican101** [ForumHulp/Export-Import-Users#9]
Is it possible to change the permissions used by this extension to make it work for user and group admins? This type of admin can't see the "export/import users"-function in the "users and groups"-tab. Actually i have to allow "Can alter board settings/check for updates", then it works. But user-admins shouldn't be allowed to do this.

**Comment by ForumHulp** [comment]
Hello
You can change the permission in the info file, search for:
'auth' => 'ext_forumhulp/exportimportusers && acl_a_board'

Change acl_a_board to a permission your admins have

**Comment by Turrican101** [comment]
Great, thank you!
